image: php:8.2

stages:
  - deploy

before_script:
  - apt-get update -y
  - apt-get install -y sshpass

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - sshpass -p $SSH_PASSWORD ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        alias composer='php /home/u625132372/composer'
        export NVM_DIR=\"\$HOME/.nvm\"
        [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"  # This loads nvm
        [ -s \"\$NVM_DIR/bash_completion\" ] && \. \"\$NVM_DIR/bash_completion\"  # This loads nvm bash_completion
        source ~/.bashrc &&
        composer --version &&
        npm --version &&
        cd $REMOTE_DIR &&
        if [ ! -d .git ]; then
          git clone $GIT_REPO_URL .;
        else
          git fetch origin main &&
          git add . &&
          git commit -m 'Temporary commit for rebase' || echo 'No changes to commit' &&
          git rebase origin/main;
        fi &&
        composer install &&
        npm install &&
        php artisan key:generate &&
        php artisan migrate:fresh --env=testing &&
        php artisan migrate --force &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache"
  only:
    - main
  environment:
    name: production
    url: http://laraforum.chang180backend.com
