image: php:8.2

stages:
  - deploy

before_script:
  - apt-get update -y
  - apt-get install -y sshpass
  - source ~/.bashrc # 加載 .bashrc 配置

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - sshpass -p $SSH_PASSWORD ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        source ~/.bashrc &&
        cd $REMOTE_DIR &&
        if [ ! -d .git ]; then
          git clone $GIT_REPO_URL .;
        else
          git fetch origin main &&
          git add . &&
          git commit -m 'Temporary commit for rebase' || echo 'No changes to commit' &&
          git rebase origin/main;
        fi &&
        composer self-update --2 &&
        composer install &&
        npm install &&
        php artisan key:generate &&
        php artisan migrate:fresh --env=testing &&
        php artisan migrate --force &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache"
  only:
    - main
  environment:
    name: production
    url: http://laraforum.chang180backend.com
