image: php:8.2

variables:
  SSH_PASSWORD: $SSH_PASSWORD
  SSH_PORT: $SSH_PORT
  SSH_USER: $SSH_USER
  SSH_HOST: $SSH_HOST
  GIT_REPO_URL: https://glpat-nxPSzZPxH7kQpwEoiCys@gitlab.com/chang180/laraforum.git
  REMOTE_DIR: ~/public_html/laraforum

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - apt-get update -y && apt-get install -y sshpass
    - sshpass -p $SSH_PASSWORD ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      cd $REMOTE_DIR &&
      if [ ! -d .git ]; then
        git clone $GIT_REPO_URL .;
      else
        git pull origin main;
      fi &&
      composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader &&
      npm install &&
      php artisan key:generate &&
      php artisan migrate:fresh --env=testing &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache"
  only:
    - main
  environment:
    name: production
    url: http://laraforum.chang180backend.com
