name: Laravel Pint
on:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Cache PHP Extensions
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql # 確保指定必要的 PHP 擴展
          key: 'php-extensions-cache-key'

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-cache-

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Laravel Pint
        run: ~/.composer/vendor/bin/pint

      - name: Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github_action@laraforum.test'
          git add .
          git commit -m "Run Laravel Pint" || exit 0
          git push
